"""sprint4_consent_records

Revision ID: 466614a36609
Revises: 7d5a80f3517d
Create Date: 2026-05-07 02:53:56.392244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '466614a36609'
down_revision: Union[str, None] = '7d5a80f3517d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_purpose', sa.String(length=100), nullable=False, comment='perfil | datos_economicos | portfolio | marketing'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.alter_column('employers', 'ruc',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256, 11 digits',
               existing_nullable=False)
    op.alter_column('employers', 'contact_name',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256',
               existing_nullable=False)
    op.alter_column('employers', 'phone',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256',
               existing_nullable=True)
    op.alter_column('employers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('employers_user_id_fkey', 'employers', type_='foreignkey')
    op.alter_column('generated_cvs', 'cv_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='wizard_based | portfolio_based | parsed',
               existing_nullable=False)
    op.alter_column('generated_cvs', 'file_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='URL firmada GCS/S3',
               existing_nullable=True)
    op.alter_column('generated_cvs', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('generated_cvs_worker_id_fkey', 'generated_cvs', type_='foreignkey')
    op.alter_column('job_offers', 'required_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('job_offers', 'preferred_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('job_offers', 'worker_type_target',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'cualquiera'::character varying"))
    op.alter_column('job_offers', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_offers', 'applications_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_job_offers_embedding', table_name='job_offers', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_job_offers_is_active', table_name='job_offers')
    op.drop_index('ix_match_events_worker_id_created_at', table_name='match_events')
    op.drop_index('ix_match_events_worker_type_created_at', table_name='match_events')
    op.create_index(op.f('ix_match_events_worker_id'), 'match_events', ['worker_id'], unique=False)
    op.create_index(op.f('ix_match_events_worker_type'), 'match_events', ['worker_type'], unique=False)
    op.alter_column('portfolio_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_portfolio_entries_embedding_hnsw', table_name='portfolio_entries', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_portfolio_entries_worker_id', table_name='portfolio_entries')
    op.drop_constraint('portfolio_entries_worker_id_fkey', 'portfolio_entries', type_='foreignkey')
    op.alter_column('search_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_service_listings_embedding_hnsw', table_name='service_listings', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_service_listings_is_active', table_name='service_listings')
    op.drop_index('ix_service_listings_worker_id', table_name='service_listings')
    op.drop_constraint('service_listings_worker_id_fkey', 'service_listings', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_users_email', table_name='users')
    op.alter_column('wizard_progress', 'job_interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('wizard_progress', 'last_saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('wizard_progress_worker_id_fkey', 'wizard_progress', type_='foreignkey')
    op.alter_column('workers', 'worker_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='primer_empleo | experiencia | oficio',
               existing_nullable=False)
    op.alter_column('workers', 'full_name',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256',
               existing_nullable=False)
    op.alter_column('workers', 'dni',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256',
               existing_nullable=False)
    op.alter_column('workers', 'phone',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='AES-256',
               existing_nullable=True)
    op.alter_column('workers', 'trade_category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='solo OFICIO',
               existing_nullable=True)
    op.alter_column('workers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_workers_district', table_name='workers')
    op.drop_index('ix_workers_embedding_hnsw', table_name='workers', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_workers_user_id', table_name='workers')
    op.drop_index('ix_workers_worker_type', table_name='workers')
    op.drop_constraint('workers_user_id_fkey', 'workers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('workers_user_id_fkey', 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_workers_worker_type', 'workers', ['worker_type'], unique=False)
    op.create_index('ix_workers_user_id', 'workers', ['user_id'], unique=False)
    op.create_index('ix_workers_embedding_hnsw', 'workers', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('ix_workers_district', 'workers', ['district'], unique=False)
    op.alter_column('workers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workers', 'trade_category',
               existing_type=sa.VARCHAR(length=50),
               comment='solo OFICIO',
               existing_nullable=True)
    op.alter_column('workers', 'phone',
               existing_type=postgresql.BYTEA(),
               comment='AES-256',
               existing_nullable=True)
    op.alter_column('workers', 'dni',
               existing_type=postgresql.BYTEA(),
               comment='AES-256',
               existing_nullable=False)
    op.alter_column('workers', 'full_name',
               existing_type=postgresql.BYTEA(),
               comment='AES-256',
               existing_nullable=False)
    op.alter_column('workers', 'worker_type',
               existing_type=sa.VARCHAR(length=20),
               comment='primer_empleo | experiencia | oficio',
               existing_nullable=False)
    op.create_foreign_key('wizard_progress_worker_id_fkey', 'wizard_progress', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.alter_column('wizard_progress', 'last_saved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wizard_progress', 'job_interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('service_listings_worker_id_fkey', 'service_listings', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_service_listings_worker_id', 'service_listings', ['worker_id'], unique=False)
    op.create_index('ix_service_listings_is_active', 'service_listings', ['is_active'], unique=False)
    op.create_index('ix_service_listings_embedding_hnsw', 'service_listings', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('service_listings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_listings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('portfolio_entries_worker_id_fkey', 'portfolio_entries', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_portfolio_entries_worker_id', 'portfolio_entries', ['worker_id'], unique=False)
    op.create_index('ix_portfolio_entries_embedding_hnsw', 'portfolio_entries', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('portfolio_entries', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_match_events_worker_type'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_worker_id'), table_name='match_events')
    op.create_index('ix_match_events_worker_type_created_at', 'match_events', ['worker_type', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_match_events_worker_id_created_at', 'match_events', ['worker_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_job_offers_is_active', 'job_offers', ['is_active'], unique=False)
    op.create_index('ix_job_offers_embedding', 'job_offers', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('job_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_offers', 'applications_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('job_offers', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('job_offers', 'worker_type_target',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'cualquiera'::character varying"))
    op.alter_column('job_offers', 'preferred_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('job_offers', 'required_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_foreign_key('generated_cvs_worker_id_fkey', 'generated_cvs', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.alter_column('generated_cvs', 'generated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_cvs', 'file_url',
               existing_type=sa.TEXT(),
               comment='URL firmada GCS/S3',
               existing_nullable=True)
    op.alter_column('generated_cvs', 'cv_type',
               existing_type=sa.VARCHAR(length=20),
               comment='wizard_based | portfolio_based | parsed',
               existing_nullable=False)
    op.create_foreign_key('employers_user_id_fkey', 'employers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employers', 'phone',
               existing_type=postgresql.BYTEA(),
               comment='AES-256',
               existing_nullable=True)
    op.alter_column('employers', 'contact_name',
               existing_type=postgresql.BYTEA(),
               comment='AES-256',
               existing_nullable=False)
    op.alter_column('employers', 'ruc',
               existing_type=postgresql.BYTEA(),
               comment='AES-256, 11 digits',
               existing_nullable=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
