"""Add job requests and contracts

Revision ID: 7d5a80f3517d
Revises: 0005
Create Date: 2026-05-06 01:38:37.177213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = '7d5a80f3517d'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_type', sa.String(length=20), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('districts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('trade_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_alerts_worker_id'), 'job_alerts', ['worker_id'], unique=False)
    
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_type', sa.String(length=20), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    
    op.create_table('job_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('office_required', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=True),
    sa.Column('max_budget', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requests_employer_id'), 'job_requests', ['employer_id'], unique=False)
    op.create_index(op.f('ix_job_requests_status'), 'job_requests', ['status'], unique=False)
    op.create_index(op.f('ix_job_requests_zone'), 'job_requests', ['zone'], unique=False)
    
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_request_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agreed_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rate_type', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=False),
    sa.Column('work_evidence', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description_done', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['job_request_id'], ['job_requests.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_employer_id'), 'contracts', ['employer_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_worker_id'), 'contracts', ['worker_id'], unique=False)
    
    op.create_table('job_request_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_request_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('proposed_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_request_id'], ['job_requests.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_request_id', 'worker_id', name='uq_application_job_worker')
    )
    op.create_index(op.f('ix_job_request_applications_job_request_id'), 'job_request_applications', ['job_request_id'], unique=False)
    op.create_index(op.f('ix_job_request_applications_worker_id'), 'job_request_applications', ['worker_id'], unique=False)
    
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rated_id', sa.UUID(), nullable=False),
    sa.Column('rater_role', sa.String(length=10), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('punctuality_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('fairness_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('worker_response', sa.String(length=200), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'rater_id', name='uq_rating_contract_rater')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass

